---
title: "MouseLiverMet2RNA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(vesalius)
library(imagerExtra)
library(Seurat)
library(ggplot2)
library(patchwork)
library(viridis)
library(RColorBrewer)
library(dplyr)
library(tvR)
library(sp)
library(grid)
library(Matrix)


# Standard libraries - just in case you are a command line fiend
library(utils)
library(stats)
library(graphics)
library(grDevices)
### Set seed
set.seed(1)
```

# List files with the bead and count data from working directory
slideBeans - CSV files with the bead locations - barcode sequence and X vs Y coordinates
slideCounts - the expression data - here sparse expressions - counts
slideTag - the descriptive aliases that will be used

```{r}
setwd("~/SlideSeq/RNA_ves_test")
slideBeads <- list.files(pattern= "bead")
slideCounts <- list.files(pattern = "sparse")
slideTag <- gsub(".bead_locations.csv","", slideBeads)

```



```{r}
  #----------------------------------------------------------------------------#
  # Loading coordinates
  #----------------------------------------------------------------------------#
#colRNAid <- slideTag[2]
RNAid <- "mouse_liver_met_2_rna_201002_04"
#colCounts <- slideCounts[2]
counts <- "mouse_liver_met_2_rna_201002_04.sparse_expression.txt"
bead <- ReadSlideSeq("mouse_liver_met_2_rna_201002_04.bead_locations.csv")
barcodes <- rownames(bead@coordinates)
#separator used in this count matrix
sep <- ","
ctmp <- read.table(counts, header = TRUE, sep=sep ) %>% na.exclude()
# Create DG matrix: i + j - row and column index - maybe a mix of row and columns - do as.counts instead
sparse <- sparseMatrix(i= ctmp[,2],j=ctmp[,1],x=ctmp[,3])

# invert/transpose/switch between rows and columns
sparse <- t(sparse)


# human bins:
hbins <- read.table("~/SlideSeq/GroupSlideSeq/hg19_1Mb_bins.txt", header = T)
hbins <- hbins$bin_ind

# Others: (mouse)
mmbins <- read.table("~/SlideSeq/GroupSlideSeq/mm10_1Mb_bins.txt", header = T)
mmbins <- mmbins$bin_ind


colnames(sparse) <- barcodes
#rownames(sparse) <- str(mmbins)
rownames(sparse) <- ctmp[,3]

  #----------------------------------------------------------------------------#
  # Creating seurat spatial object
  # NOTE this code is taken from the Seurat source code as it does not seem that
  # Slide seq loading function are all exported
  # If this has been updated - this section can be changed accordingly
  #----------------------------------------------------------------------------#
ctmp <- CreateSeuratObject(sparse, assay ="Spatial")
bead <- bead[Cells(x = ctmp)]
  DefaultAssay(object = bead) <- "Spatial"
  ctmp[["slice1"]] <- bead
  #ctmp <- subset(ctmp, subset = nFeature_Spatial > 100 & nFeature_Spatial < 4500 & percent.mt < 5)
  #----------------------------------------------------------------------------#
  # Seuart pre-processing steps
  #----------------------------------------------------------------------------#
  ctmp <- NormalizeData(ctmp)
  ctmp <- FindVariableFeatures(ctmp, nfeatures = 2000)
  ctmp <- ScaleData(ctmp)

  #----------------------------------------------------------------------------#
  # Embed PCA loading into the RGB colour space.
  #----------------------------------------------------------------------------#
  ctmp <- rgbPCA(ctmp, slices = 3 , conserveSparse = FALSE)
  #### Remember no split ! all in the same file!!!!!
  exportRGB.csv(ctmp,file = paste0(slideTag[i],"_rgbExport.csv"),split=F)

  image <- buildImageArray(ctmp,filterThreshold=0.9975,resolution=20, cores=5)

  image <- equalizeHistogram(image,sleft = 2.5, sright=2.5,invert =T)


  image <- regulariseImage(image, lambda = 10,
                                niter = 200, normalise=T)
  image <- iterativeSegmentation.array(image, colDepth = 6,
                                            smoothIter = 20,
                                            method = c("iso","median"),
                                            sigma=1.5,box = 10,
                                            useCenter = T)
  image <- isolateTerritories.array(image,
                                          captureRadius = 0.008,
                                          minBar = 40)
  pdf(paste0(slideTag[i],"_image.pdf"))
  imagePlot(image)
  print(territoryPlot(image,cex=10))
  dev.off()
  write.csv(image, file = paste0(slideTag[i],"_ImageExport.csv"))
}
```


